apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: slander/spike-ring:v0.1.8
        ports:
        - containerPort: 8080
