apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: slander/spike-ring:v0.1.27
        ports:
        - containerPort: 8080
      - name: spike-python
        image: slander/spike-python:v0.1.25
        ports:
        - containerPort: 5000
      - name: spike-clojurescript
        image: slander/spike-clojurescript:v0.1.27
        ports:
        - containerPort: 3000
